-- Edificios, núcleos, ascensores y conexiones (docs/reglas/asignacion.md). Son datos, no código:
-- para corregir un cartel o medir una caminata, migración nueva. ElevatorLayoutValidator los valida al arrancar.

CREATE TABLE building (
    code      VARCHAR(32) NOT NULL PRIMARY KEY,
    name      VARCHAR(64) NOT NULL,
    min_floor INT         NOT NULL,
    max_floor INT         NOT NULL,
    CHECK (min_floor <= max_floor)
);

-- Núcleo: grupo de ascensores de un edificio; es el nodo del grafo de conexiones.
CREATE TABLE core (
    code          VARCHAR(8)  NOT NULL PRIMARY KEY,
    building_code VARCHAR(32) NOT NULL REFERENCES building (code)
);

-- usage_type: COMMON, o dedicado a docentes (TEACHERS) o a movilidad reducida (REDUCED_MOBILITY).
CREATE TABLE elevator (
    code       VARCHAR(8)  NOT NULL PRIMARY KEY,
    core_code  VARCHAR(8)  NOT NULL REFERENCES core (code),
    usage_type VARCHAR(32) NOT NULL CHECK (usage_type IN ('COMMON', 'TEACHERS', 'REDUCED_MOBILITY')),
    active     BOOLEAN     NOT NULL
);

-- Pisos donde para cada ascensor: una lista, no un rango (L2 alta saltea el −1 y el 1, IND2 el 1).
CREATE TABLE elevator_floor (
    elevator_code VARCHAR(8) NOT NULL REFERENCES elevator (code),
    floor_number  INT        NOT NULL,
    PRIMARY KEY (elevator_code, floor_number)
);

-- Paso entre dos núcleos en los pisos from_floor a to_floor. NULL = a medir / a confirmar (#22).
CREATE TABLE core_connection (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    core_a_code          VARCHAR(8) NOT NULL REFERENCES core (code),
    core_b_code          VARCHAR(8) NOT NULL REFERENCES core (code),
    from_floor           INT        NOT NULL,
    to_floor             INT        NOT NULL,
    walking_time_seconds INT CHECK (walking_time_seconds > 0),
    accessible           BOOLEAN,
    CHECK (core_a_code <> core_b_code),
    CHECK (from_floor <= to_floor)
);

INSERT INTO building (code, name, min_floor, max_floor) VALUES
    ('LIMA',          'Lima',          -4, 10),
    ('INDEPENDENCIA', 'Independencia', -4, 11);

INSERT INTO core (code, building_code) VALUES
    ('L1',   'LIMA'),
    ('L2',   'LIMA'),
    ('L3',   'LIMA'),
    ('IND1', 'INDEPENDENCIA'),
    ('IND2', 'INDEPENDENCIA');

-- IND1 05 y 06 no están numerados en el edificio: son códigos nuestros.
INSERT INTO elevator (code, core_code, usage_type, active) VALUES
    ('33', 'IND2', 'COMMON',           TRUE),
    ('34', 'IND2', 'COMMON',           TRUE),
    ('05', 'IND1', 'TEACHERS',         TRUE),
    ('06', 'IND1', 'REDUCED_MOBILITY', TRUE),
    ('10', 'L3',   'COMMON',           TRUE),
    ('11', 'L3',   'COMMON',           TRUE),
    ('12', 'L3',   'COMMON',           TRUE),
    ('13', 'L3',   'COMMON',           TRUE),
    ('14', 'L3',   'COMMON',           TRUE),
    ('15', 'L3',   'COMMON',           TRUE),
    ('07', 'L2',   'COMMON',           TRUE),
    ('08', 'L2',   'COMMON',           TRUE),
    ('35', 'L2',   'COMMON',           TRUE),
    ('36', 'L2',   'COMMON',           TRUE),
    ('01', 'L1',   'COMMON',           TRUE),
    ('02', 'L1',   'COMMON',           TRUE),
    ('03', 'L1',   'COMMON',           TRUE),
    ('04', 'L1',   'COMMON',           TRUE);

-- Una fila por batería, con los pisos tal cual el cartel (sin generate_series: tiene que correr en H2).
-- IND2 33 y 34: −4 a 11, sin el 1.
INSERT INTO elevator_floor (elevator_code, floor_number)
SELECT e.code, f.n FROM elevator e
CROSS JOIN (VALUES (-4), (-3), (-2), (-1), (0), (2), (3), (4), (5), (6), (7), (8), (9), (10), (11)) AS f (n)
WHERE e.code IN ('33', '34');

-- IND1 05 y 06: −4 a 10.
INSERT INTO elevator_floor (elevator_code, floor_number)
SELECT e.code, f.n FROM elevator e
CROSS JOIN (VALUES (-4), (-3), (-2), (-1), (0), (1), (2), (3), (4), (5), (6), (7), (8), (9), (10)) AS f (n)
WHERE e.code IN ('05', '06');

-- L3 10 a 15: −3 a 10.
INSERT INTO elevator_floor (elevator_code, floor_number)
SELECT e.code, f.n FROM elevator e
CROSS JOIN (VALUES (-3), (-2), (-1), (0), (1), (2), (3), (4), (5), (6), (7), (8), (9), (10)) AS f (n)
WHERE e.code IN ('10', '11', '12', '13', '14', '15');

-- L2 batería baja 07 y 08: −4 a 5.
INSERT INTO elevator_floor (elevator_code, floor_number)
SELECT e.code, f.n FROM elevator e
CROSS JOIN (VALUES (-4), (-3), (-2), (-1), (0), (1), (2), (3), (4), (5)) AS f (n)
WHERE e.code IN ('07', '08');

-- L2 batería alta 35 y 36: −2, 0 y 2 a 10 (sin el −1 ni el 1).
INSERT INTO elevator_floor (elevator_code, floor_number)
SELECT e.code, f.n FROM elevator e
CROSS JOIN (VALUES (-2), (0), (2), (3), (4), (5), (6), (7), (8), (9), (10)) AS f (n)
WHERE e.code IN ('35', '36');

-- L1 01 a 04: −3 a 7.
INSERT INTO elevator_floor (elevator_code, floor_number)
SELECT e.code, f.n FROM elevator e
CROSS JOIN (VALUES (-3), (-2), (-1), (0), (1), (2), (3), (4), (5), (6), (7)) AS f (n)
WHERE e.code IN ('01', '02', '03', '04');

-- Cadena IND2 – IND1 – L3 – L2 – L1, en los pisos que comparten. IND2 no para en el 1, así que
-- IND2–IND1 va en dos tramos (−4 a 0 y 2 a 10) en lugar del "−4 a 10" de la tabla de asignacion.md.
INSERT INTO core_connection (core_a_code, core_b_code, from_floor, to_floor, walking_time_seconds, accessible) VALUES
    ('IND2', 'IND1', -4, 0,  NULL, NULL),
    ('IND2', 'IND1', 2,  10, NULL, NULL),
    ('IND1', 'L3',   -3, 10, NULL, NULL),
    ('L3',   'L2',   -3, 10, NULL, NULL),
    ('L2',   'L1',   -3, 7,  NULL, NULL);
